/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.components;

import javax.swing.JButton;
import javax.swing.JLabel;
import vista.usuario.citasPanel;

/**
 *
 * @author christian
 */
public class menu extends javax.swing.JPanel {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCrearUsuaros = new javax.swing.JButton();
        btnCrearPacentes = new javax.swing.JButton();
        btnCrearCitas = new javax.swing.JButton();
        btnCrearOdontologo = new javax.swing.JButton();
        btnGestionarUsuarios = new javax.swing.JButton();
        btnGestionarOdontologos = new javax.swing.JButton();
        btnGestionarPacientes = new javax.swing.JButton();
        btnGestionarCitas = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(143, 166, 143));

        jLabel1.setBackground(new java.awt.Color(36, 38, 37));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(36, 38, 37));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/path1.png"))); // NOI18N

        btnCrearUsuaros.setText("usuarios");

        btnCrearPacentes.setText("pacientes");

        btnCrearCitas.setText("citas");
        btnCrearCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCitasActionPerformed(evt);
            }
        });

        btnCrearOdontologo.setText("crear odontologos");

        btnGestionarUsuarios.setText("gestionar Usuarios");

        btnGestionarOdontologos.setText("gestionar Odontologos");

        btnGestionarPacientes.setText("gestionar pacientes");

        btnGestionarCitas.setText("gestionar citas");
        btnGestionarCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionarCitasMouseClicked(evt);
            }
        });
        btnGestionarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarCitasActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("Cerrar sesion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnCrearPacentes, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnCrearCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnCrearUsuaros, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnCrearOdontologo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnGestionarOdontologos, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnGestionarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnGestionarCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnGestionarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnCrearPacentes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnCrearCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnCrearUsuaros, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnCrearOdontologo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnGestionarOdontologos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnGestionarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnGestionarCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarCitasMouseClicked

    }//GEN-LAST:event_btnGestionarCitasMouseClicked

    private void btnGestionarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarCitasActionPerformed

    private void btnCrearCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearCitasActionPerformed

    public JButton getBtnCrearCitas() {
        return btnCrearCitas;
    }

    public void setBtnCrearCitas(JButton btnCrearCitas) {
        this.btnCrearCitas = btnCrearCitas;
    }

    public JButton getBtnCrearPacentes() {
        return btnCrearPacentes;
    }

    public void setBtnCrearPacentes(JButton btnCrearPacentes) {
        this.btnCrearPacentes = btnCrearPacentes;
    }

    public JButton getBtnCrearUsuarios() {
        return btnCrearUsuaros;
    }

    public void setBtnCrearUsuarios(JButton btnCrearUsuaros) {
        this.btnCrearUsuaros = btnCrearUsuaros;
    }

    public JButton getBtnCrearOdontologo() {
        return btnCrearOdontologo;
    }

    public void setBtnCrearOdontologo(JButton btnCrearOdontologo) {
        this.btnCrearOdontologo = btnCrearOdontologo;
    }

    public JButton getBtnGestionarOdontologos() {
        return btnGestionarOdontologos;
    }

    public void setBtnGestionarOdontologos(JButton btnGestionarOdontologos) {
        this.btnGestionarOdontologos = btnGestionarOdontologos;
    }

    public JButton getBtnGestionarPacientes() {
        return btnGestionarPacientes;
    }

    public void setBtnGestionarPacientes(JButton btnGestionarPacientes) {
        this.btnGestionarPacientes = btnGestionarPacientes;
    }

    public JButton getBtnGestionarUsuarios() {
        return btnGestionarUsuarios;
    }

    public void setBtnGestionarUsuarios(JButton btnGestionarUsuarios) {
        this.btnGestionarUsuarios = btnGestionarUsuarios;
    }

    public JButton getBtnGestionarCitas() {
        return btnGestionarCitas;
    }

    public void setBtnGestionarCitas(JButton btnGestionarCitas) {
        this.btnGestionarCitas = btnGestionarCitas;
    }

    public JButton getBtnCerrarSesion() {
        return btnCerrarSesion;
    }

    public void setBtnCerrarSesion(JButton btnCerrarSesion) {
        this.btnCerrarSesion = btnCerrarSesion;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCrearCitas;
    private javax.swing.JButton btnCrearOdontologo;
    private javax.swing.JButton btnCrearPacentes;
    private javax.swing.JButton btnCrearUsuaros;
    private javax.swing.JButton btnGestionarCitas;
    private javax.swing.JButton btnGestionarOdontologos;
    private javax.swing.JButton btnGestionarPacientes;
    private javax.swing.JButton btnGestionarUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public Object getBtnCitas() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
