/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.usuario;

import controlador.Controlador;
import controlador.MenuControlador;
import java.awt.BorderLayout;
import java.awt.GridBagLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import modelo.PersonaJson;
import vista.components.menu;

/**
 *
 * @author sofia
 */
public class usuarioGestionarPaciente extends javax.swing.JFrame {

  private PersonaJson personaModel;
  private Controlador controlador;

  public usuarioGestionarPaciente() {
    initComponents();
    this.controlador = controlador;

    personaModel = new PersonaJson();
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    setLocationRelativeTo(null);
    setLayout(new BorderLayout());

    menu menuComponent = new menu();
    add(menuComponent, BorderLayout.WEST);

    // ¡Aquí ya puedes pasarlo correctamente!
    new MenuControlador(menuComponent, personaModel, "usuario", controlador);

    JPanel panelFormulario = new JPanel(new GridBagLayout());
    panelFormulario.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
    add(panelFormulario, BorderLayout.CENTER);

    pack();
    revalidate();
    repaint();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        btlAgenda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 700));
        setMinimumSize(new java.awt.Dimension(1100, 700));

        jLabel1.setText("Odontologos Registrados");

        btnEliminar.setText("Eliminar");

        btlAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Identificacion", "Apellidos", "Telefono", "Direccion", "Fecha", "Correo"
            }
        ));
        jScrollPane2.setViewportView(btlAgenda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addComponent(btnEliminar))
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(316, 316, 316))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnEliminar)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  public JTable getBtlAgenda() {
    return btlAgenda;
  }

  public void setBtlAgenda(JTable btlAgenda) {
    this.btlAgenda = btlAgenda;
  }

  // public JButton getBtnBuscar() {
  // return btnBuscar;
  // }
  //
  // public void setBtnBuscar(JButton btnBuscar) {
  // this.btnBuscar = btnBuscar;
  // }


  public JButton getBtnEliminar() {
    return btnEliminar;
  }

  public void setBtnEliminar(JButton btnEliminar) {
    this.btnEliminar = btnEliminar;
  }

  public JTextField getTxtBuscar() {
    return txtBuscar;
  }

  public void setTxtBuscar(JTextField txtBuscar) {
    this.txtBuscar = txtBuscar;
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable btlAgenda;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
